### ISSUE TITLE
Criar ambiente docker

### ISSUE THREAD

**Issue by PauloKeller** [FATEC-SJC-NoName/back-chat-app#21]
- [x] Adicionar dependências
- [x] Criar dockerfile banco
- [x] Criar dockerfile app
- [x] Criar docker-componse
- [x] Configurar variaveis de ambiente

**Comment by PauloKeller** [comment]
- [ ] Criar docker file
- [ ] Criar docker compose
- [ ] Testar configurações
