### ISSUE TITLE
Implementação de diferentes perfis de gerênciamento

### ISSUE THREAD

**Issue by PauloKeller** [FATEC-SJC-NoName/back-chat-app#33]
- [x] Adicionar dependências
- [x] Criar configuração
- [x] Atualizar modulos
- [x] Adicionar UserDetailsService
- [x] Configurar Jwt
- [x] Configurar Roles
- [x] Adicionar authenticação stateless
- [x] Adicionar Jwt Utils
- [x] Adicionar login por usuarios da base
- [x] Vincular roles aos usuários
- [x] Permitir acesso as outras rotas publicas da api
- [x] Testar criar usuario e login
